[package]
name = "solrcopy"
version = "0.6.0"
edition = "2021"

authors = ["Juarez Rudsatz <juarezr@gmail.com>"]
description = "Tool for backup and restore of documents stored in cores of solr"
homepage = "https://github.com/juarezr/solrcopy"
repository = "github.com:juarezr/solrcopy.git"
license = "gpl-3.0-or-later"
readme = "README.md"
categories = ["command-line-utilities"]
keywords = ["solr", "dataimport", "dih", "fulltext-search", "apache-solr"]

[dependencies]
clap = { version = "4.5.*", features = ["derive", "env", "color"] }
clap_complete = "4.5.*"
clap_mangen = "0.2.*"
regex = "1.10.*"
url = "2.5.*"
lazy_static = "1.5.*"
ureq = { version = "2.10.*", features = ["tls", "charset", "cookies", "brotli"] }
zip = { version = "2.2.*",  features = ["deflate", "time"] }
indicatif = "0.17.*"
chrono = "0.4.*"
glob = "0.3.*"
log = "0.4.*"
simplelog = "0.12.*"
crossbeam-channel = "0.5.1"
crossbeam-utils = "0.8.*"
ctrlc = { version = "3.4.*", features = ["termination"] }

[badges]
travis-ci = { repository = "juarezr/solrcopy", branch = "master" }

[profile.release]
strip = "debuginfo"
lto = true

# Shell completions are generated by running:
# $ cargo run --release -- completion -all -o target

[package.metadata.deb]
# see: https://github.com/kornelski/cargo-deb
section = "utils"
priority = "optional"
changelog = "changelog.txt"
assets = [
  ["target/release/solrcopy", "usr/bin/", "755"],
  ["LICENSE", "usr/share/doc/solrcopy/", "644"],
  ["changelog.txt", "usr/share/doc/solrcopy/", "644"],
  ["README.md", "usr/share/doc/solrcopy/README", "644"],
  ["target/assets/solrcopy.bash", "usr/share/bash-completion/completions/solrcopy", "644"],
  ["target/assets/solrcopy.fish", "usr/share/fish/vendor_completions.d/solrcopy.fish", "644"],
  ["target/assets/_solrcopy", "usr/share/zsh/vendor-completions/", "644"],
  ["target/assets/solrcopy.1", "usr/share/man/man1/", "644"],
]
extended-description = """\
Solrcopy is a command for doing backup and restore of documents stored on Solr \
cores. It let you filter docs by using a expression, limit quantity, define order\
and desired columns to export. The data is stored as json inside local zip files.\
It is agnostic to data format, content and storage place. \
Because of this data is restored exactly as extracted and your responsible for \
extracting, storing and updating the correct data in correct cores."""

[package.metadata.generate-rpm]
# see: https://github.com/cat-in-136/cargo-generate-rpm
assets = [
  { source = "target/release/solrcopy", dest = "/usr/bin/", mode = "755" },
  { source = "LICENSE", dest = "/usr/share/doc/solrcopy/", mode = "644" },
  { source = "changelog.txt", dest = "/usr/share/doc/solrcopy/", mode = "644" },
  { source = "README.md", dest = "/usr/share/doc/solrcopy/README", mode = "644" },
  { source = "target/assets/solrcopy.bash", dest = "/usr/share/bash-completion/completions/solrcopy", mode = "644" },
  { source = "target/assets/solrcopy.fish", dest = "/usr/share/fish/vendor_completions.d/solrcopy.fish", mode = "644" },
  { source = "target/assets/_solrcopy", dest = "/usr/share/zsh/vendor-completions/", mode = "644" },
  { source = "target/assets/solrcopy.1", dest = "/usr/share/man/man1/", mode = "644"},
]

# [profile.release]
# # used for cargo flamegraph --bin solrcopy --  <params>
# debug = true
# # echo -1 | sudo tee /proc/sys/kernel/perf_event_paranoid

# end of the file
