# Testing Solrcopy using a container with Solr

#$ cargo install --force cargo-make

#$ cargo make all

[tasks.before]
command = "docker"
args = ["compose", "-f", "./docker/docker-compose.yml", "up", "-d"]

[tasks.after]
command = "docker"
args = ["compose", "-f", "./docker/docker-compose.yml", "down", "-v"]

[tasks.all]
dependencies = ["after", "before"]

[tasks.example]
script_runner = "@rust"
script = '''
//! ```cargo
//! [dependencies]
//! envmnt = "*"
//! ```
fn main() {
    let value = envmnt::get_or("PATH", "NO PATH VAR DEFINED");
    println!("Path Value: {}", &value);
}
'''
