#### SETTINGS FOR AUTO FORMATTING SOURCES ####

## Before commiting run `cargo fmt` for all source files
## Checking of formatting is configured in github CI at file:
##   - ./github/workflows/build-test-and-lint.yml

edition = "2024"
newline_style = "Unix"
# max_width = 100       # default 100
# tab_spaces = 4        # default 4

## Works on Stable and Nighly ##

fn_params_layout = "Compressed"           # Default: "Wide"
use_field_init_shorthand = true
use_small_heuristics = "Max"          # Default: "Default"
use_try_shorthand = true

## Works on Nighly only ##

# condense_wildcard_suffixes = true
# format_code_in_doc_comments = true
# format_strings = true
# merge_imports = true
# normalize_comments = true

## Works on Nighly but Stable reverts it's changes ##

# enum_discrim_align_threshold = 40
# fn_single_line = true
# imports_indent = "Visual"
# match_block_trailing_comma = true
# overflow_delimited_expr = true
# struct_field_align_threshold = 40
# trailing_semicolon = true
# version = "Two"

# unstable_features = true

## END OF SETTINGS ##

