#!/usr/bin/env -S bash -x -c 'docker compose up -d'

services:
  solr:
    container_name: solr4test
    image: solr:slim
    ports:
     - "8983:8983"
    volumes:
      - data:/var/solr
    command:
      - solr-demo
      - solr create -c target
      - solr create -c films
      - solr post -c films /opt/solr/example/films/films.xml
      - solr create -c films2
      - solr post -c films2 /opt/solr/example/films/films.json
volumes:
  data:
