#!/usr/bin/env -S bash -x -c 'docker compose up --no-recreate --detach solr'

version: '3'
services:
  solr:
    container_name: solr
    image: solr:slim
    ports:
     - "8983:8983"
    volumes:
      - data:/var/solr
    command:
      - solr-demo
      - solr create_core -c target
volumes:
  data:
