#!/usr/bin/env -S bash -x -c 'docker compose up -d'

services:
  solr:
    container_name: solr4test
    image: solr:slim
    ports:
     - "8983:8983"
    volumes:
      - data:/var/solr
    configs:
      - source: solr-test-setup.sh
        target: /opt/solr/docker/scripts/solr-test-setup
        mode: 0755
    healthcheck:
      test: solr status || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    command:
      # - solr-demo
      - solr-test-setup
volumes:
  data:

configs:
  solr-test-setup.sh:
    content: |
      #!/bin/bash

      # Configure a Solr demo and then run solr in the foreground

      set -euo pipefail

      if test -n "${VERBOSE:-}"; then set -x; fi

      source run-initdb

      if [ -d /var/solr/data/demo ]; then
        echo "Solr cores already exists; skipping demo creation"
      else
        start-local-solr

        /opt/solr/bin/solr create -c demo
        /opt/solr/bin/solr post -c demo /opt/solr/example/exampledocs/*.xml
        /opt/solr/bin/solr post -c demo /opt/solr/example/exampledocs/books.json
        /opt/solr/bin/solr post -c demo /opt/solr/example/exampledocs/books.csv

        /opt/solr/bin/solr create -c target

        /opt/solr/bin/solr create -c films
        /opt/solr/bin/solr post -c films /opt/solr/example/films/films.xml

        /opt/solr/bin/solr create -c films2
        /opt/solr/bin/solr post -c films2 /opt/solr/example/films/films.json

        stop-local-solr
      fi

      exec solr-fg

      # END OF SCRIPT #
