name: 'Report Workflow Information'
description: 'Reusable action meant to be used in workflow steps'
branding:
  icon: 'watch'
  color: 'green'

inputs:
  title:
    description: 'A reference to put in the report title'
    required: true
    default: 'the Job'
  arguments:
    description: 'Inputs used in the job step'
    required: false
  environment:
    description: 'Environment variables used in the job step'
    required: false
  variables:
    description: 'Variables used in the job step'
    required: false
outputs:
  status:
    description: "Return report status"
    value: ${{ steps.report_workflow_generation.outputs.status }}
runs:
  using: "composite"
  steps:
    - name: Report Workflow Information
      id: report_workflow_generation
      shell: bash
      run: |
        echo "status=started" >> "${GITHUB_OUTPUT}";
        dump_ctx(){
          printf '\n### %s Context\n\n\n```\n' "${1:-Unknown}" >> "${GITHUB_STEP_SUMMARY}";
          cat /dev/stdin || printf 'Failed to dump context for %s\n' "${1:-Unknown}" >> "${GITHUB_STEP_SUMMARY}";
          printf '\n```\n\nArguments: %s\n\n' "$*" >> "${GITHUB_STEP_SUMMARY}";
        };

        printf '# Workflow Information on ${{ inputs.title }}\n\n' >> "${GITHUB_STEP_SUMMARY}";
        printf '\n## Event Information\n\n' >> "${GITHUB_STEP_SUMMARY}";
        echo "- github.ref_name: ${{ github.ref_name }}" >> "${GITHUB_STEP_SUMMARY}";
        echo "- github.sha: ${{ github.sha }}" >> "${GITHUB_STEP_SUMMARY}";

        printf '\n## Context Information\n\n' >> "${GITHUB_STEP_SUMMARY}";
        echo "${{ toJson(github) }}" | dump_ctx "GitHub";
        echo "${{ toJson(job) }}" | dump_ctx "Job";
        echo "${{ toJson(runner) }}" | dump_ctx "Runner";
        echo "${{ inputs.arguments }}" | dump_ctx "Inputs";
        echo "${{ inputs.environment }}" | dump_ctx "Environment";
        echo "${{ inputs.variables }}" | dump_ctx "Variables";
        echo "${{ toJson(inputs) }}" | dump_ctx "Composite Inputs";

        echo "status=finished" >> "${GITHUB_OUTPUT}";

