name: 'Report Workflow Information'
description: 'Reusable action meant to be used in workflow steps'
inputs:
  title:
    description: 'A title for the report'
    required: true
outputs:
  status:
    description: "Return report status"
    value: ${{ steps.report_workflow_generation.outputs.status }}
runs:
  using: "composite"
  steps:
    - name: Report Workflow Information
      id: report_workflow_generation
      shell: bash
      run: |
        echo "status=started" >> "${GITHUB_OUTPUT}";
        dump_ctx(){
          printf '\n### %s Context\n\n\n```\n' "${1:-Unknown}" >> "${GITHUB_STEP_SUMMARY}";
          cat /dev/stdin || printf 'Failed to dump context for %s\n' "${1:-Unknown}" >> "${GITHUB_STEP_SUMMARY}";
          printf '\n```\n\nArguments: %s\n\n' "$*" >> "${GITHUB_STEP_SUMMARY}";
        };

        printf '# Workflow Information on ${{ inputs.title }}\n\n' >> "${GITHUB_STEP_SUMMARY}";
        printf '\n## Event Information\n\n' >> "${GITHUB_STEP_SUMMARY}";
        echo "- github.ref_name: ${{ github.ref_name }}" >> "${GITHUB_STEP_SUMMARY}";
        echo "- github.sha: ${{ github.sha }}" >> "${GITHUB_STEP_SUMMARY}";

        printf '\n## Context Information\n\n' >> "${GITHUB_STEP_SUMMARY}";
        echo "${{ toJson(github) }}" | dump_ctx "GitHub";
        echo "${{ toJson(job) }}" | dump_ctx "Job";
        echo "${{ toJson(runner) }}" | dump_ctx "Runner";
        echo "${{ toJson(inputs) }}" | dump_ctx "Inputs";
        echo "${{ toJson(vars) }}" | dump_ctx "Variables";
        echo "${{ toJson(env) }}" | dump_ctx "Environment";

        echo "status=finished" >> "${GITHUB_OUTPUT}";

