## Workflow triggered when issuing a new release

on:
  release:
    types: [published]

name: build-release

jobs:
  releasing:
    name: releasing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build: [linux, win-gnu, macos]
        # rustc --print target-list
        include:
        - build: linux
          os: linux
          target: x86_64-unknown-linux-gnu
          channel: stable
          cross: false
        - build: win-gnu
          os: windows
          target: x86_64-pc-windows-gnu
          channel: stable
          cross: true
        - build: macos
          os: macos
          target: x86_64-apple-darwin
          channel: stable
          cross: true
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELEASE_VERSION: ${{ github.event.release.tag_name }}
      TARGET_DIR: target/${{ matrix.target }}/release
      ARTIFACT_DIR: target/${{ matrix.target }}/artifacts
      ARTIFACT_NAME: solrcopy-${{ github.event.release.tag_name }}-${{ matrix.target }}
    
    steps:
      - name: Get release version
        run: |
          echo "github.event.release.tag_name : ${{ github.event.release.tag_name }}"
          echo "github.event.release.upload_url : ${{ github.event.release.upload_url }}"
          echo "github.event_path : ${{ github.event_path }}"

      - name: Install rpm tools
        if: matrix.os == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends rpm

      - name: Install mingw toolchain
        if: matrix.os == 'windows'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends mingw-w64

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install cargo plugins
        uses: actions-rs/cargo@v1
        if: matrix.os == 'linux'
        with:
          command: install
          args: cargo-deb cargo-generate-rpm

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Create local artifact folders
        run: mkdir -p ${{ env.ARTIFACT_DIR }} target/assets

      - name: Generate Assets
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.cross }}
          command: run
          args: run -- generate --all --output-dir target/assets

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.cross }}
          command: build
          args: --release --verbose --target=${{ matrix.target }}

      - name: Make a tar package for release (linux and macos)
        if: matrix.os == 'linux' || matrix.os == 'macos'
        run: tar --directory=${{ env.TARGET_DIR }} -czvf ${{ env.ARTIFACT_DIR }}/${{ env.ARTIFACT_NAME }}.tar.gz solrcopy

      - name: Make a Windows zip package
        if: matrix.os == 'windows'
        run: |
          ls -lshFGHL ${{ env.TARGET_DIR }}
          zip -j ${{ env.ARTIFACT_DIR }}/${{ env.ARTIFACT_NAME }}.zip ${{ env.TARGET_DIR }}/solrcopy.exe

      - name: Make the debian package
        uses: actions-rs/cargo@v1
        if: matrix.os == 'linux'
        with:
          command: deb
          args: --profile release --verbose --strip --no-build --target=${{ matrix.target }} --output ${{ env.ARTIFACT_DIR }}/${{ env.ARTIFACT_NAME }}.deb

      - name: Make a rpm package
        uses: actions-rs/cargo@v1
        if: matrix.os == 'linux'
        with:
          command: generate-rpm
          args: --profile release --target=${{ matrix.target }} --output ${{ env.ARTIFACT_DIR }}/${{ env.ARTIFACT_NAME }}.rpm

      - name: Upload Debian Package
        uses: actions/upload-release-asset@v1
        if: matrix.os == 'linux'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/${{ matrix.target }}/debian/solrcopy_${{ env.RELEASE_VERSION }}_amd64.deb
          asset_name: solrcopy_${{ env.RELEASE_VERSION }}_amd64.deb
          asset_content_type: application/vnd.debian.binary-package

      - name: Upload RPM Package
        uses: actions/upload-release-asset@v1
        if: matrix.os == 'linux'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.TARGET_DIR }}/solrcopy-${{ env.RELEASE_VERSION }}.rpm
          asset_name: solrcopy-${{ env.RELEASE_VERSION }}.rpm
          asset_content_type: application/x-rpm

      - name: Upload linux binary package
        uses: actions/upload-release-asset@v1
        if: matrix.os == 'linux' || matrix.os == 'macos'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.ARTIFACT_DIR }}/${{ env.ARTIFACT_NAME }}.tar.gz
          asset_name: ${{ env.ARTIFACT_NAME }}.tar.gz
          asset_content_type: application/octet-stream

      - name: Upload windows binary package
        uses: actions/upload-release-asset@v1
        if: matrix.os == 'windows'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.ARTIFACT_DIR }}/${{ env.ARTIFACT_NAME }}.zip
          asset_name: ${{ env.ARTIFACT_NAME }}.zip
          asset_content_type: application/octet-stream

# end of file
