# https://github.com/actions-rs/audit-check#scheduled-audit

name: Monthly Security Audit
on:
  schedule:
    - cron: '3 2 1 * *'
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Run security audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
